apiVersion: v2
name: tempo-tracing
description: Configure the Tempo Operator (distributed tracing).
version: 1.0.3
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/tempo-tracing
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/tempo-operator-icon.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - tempo
  - tracing
  - observability
  - distributed-tracing
  - opentelemetry
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
    - kind: fixed
      description: fixed issue with serviceaccount template
    - kind: added
      description: added labels to serviceaccount template
    - kind: added
      description: added description for storageSize parameter
