apiVersion: v2
name: quay-registry-setup
description: Deploy and configure Red Hat Quay Registry.
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/quay-registry-setup
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/quay-icon.png
version: 2.0.1
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - management tool
  - registry
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Signing Chart
    - kind: added
      description: updated to helper-status-checker v4
    - kind: added
      description: README
    - kind: added
      description: added tpl chart
    - kind: added
      description: using some templates
    - kind: fixed
      description: Postgres does not allow replica override.
    - kind: fixed
      description: Removed hardcoded nodeSelector from Namespace resource. This might be added later as variable
    - kind: added
      description: using new tpl function bindtoNode
    - kind: added
      description: This big update moved Config Generation into this chart and included a Job that is able to inject the certificate into the Quay configration. Moreover, any storage type is now supported to be generated by this chart.
    - kind: fixed
      description: Fixed some default configuration values
