apiVersion: v2
name: minio-configurator
description: A Chart to automate the bucket creation and configuration for MINIO Object Storage
version: 1.0.10
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
dependencies:
  - name: tpl
    version: ~1.0.22
    repository: https://charts.stderr.at/
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/minio-configurator
icon: https://raw.githubusercontent.com/tjungbauer/helm-charts/gh-pages/images/minio.png
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - minio
  - storage
  - clusterconfig
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
    - kind: changed
      description: changed the image to the new minio-client-tools image
    - kind: fixed
      description: fixed the issue with the findutils package
