apiVersion: v2
name: admin-networkpolicies
description: Configure AdminNetworkPolicy and BaselineNetworkPolicy resources for a cluster.
version: 1.0.4
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/admin-networkpolicies
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/policy.png
dependencies:
  - name: tpl
    version: ~1.0.13
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
  - https://blog.stderr.at/openshift/2024/11/introducting-adminnetworkpolicies/
keywords:
  - security
  - clusterconfig
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: initial release
    - kind: added
      description: fixes and adding README
    - kind: added
      description: added support for portEndNumber
    - kind: added
      description: fixing portRange implementation
