{{- with .Values.gitopsclusterinstance }}
{{ if eq ( .clusterAdmin | toString) "enabled" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gitopsclusterinstance.rolename" $ }}-role
  labels:
    {{- include "common.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gitopsclusterinstance.serviceAccountName" $ }}
    namespace: {{ .namespace.name | default "openshift-operators" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}
{{- end }}