{{- if eq ( .Values.enabled | toString) "true" }}
{{- with .Values }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-odf-bucket-secret
  namespace:  {{ .namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "3" | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      name: create-odf-secret
    spec:
      containers:
        - name: create-odf-secret
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              # Sleeping before starting with the work, to be sure the bucket has been created.
              SLEEPER_TMP=0

              printf "Waiting 20 seconds before I start with the generation of the configuration\n"

              {{ include "tpl.sleeptimer" (dict "sleeptimer" "20")  | nindent 14 }}


              printf "\nTrying to create the required secret file\n"

              bucket_user=`cat /tmp/bucket-secret/AWS_ACCESS_KEY_ID`

              bucket_secret=`cat /tmp/bucket-secret/AWS_SECRET_ACCESS_KEY`

              bucket_name=`cat /tmp/odf-bucket/BUCKET_NAME`

              bucket_host=`cat /tmp/odf-bucket/BUCKET_HOST`

              bucket_region=`cat /tmp/odf-bucket/BUCKET_REGION`

              oc create secret generic {{ .secretname }} \
              --from-literal {{ .keys.access_key_id | default "access_key_id" }}=${bucket_user} \
              --from-literal {{ .keys.access_key_secret | default "access_key_secret" }}=${bucket_secret} \
              --from-literal {{ .keys.bucket | default "bucket" }}=${bucket_name} \
              --from-literal {{ .keys.endpoint | default "endpoint" }}=https://${bucket_host} \
              {{- if .set_region }}
              --from-literal {{ .keys.region | default "region" }}=${bucket_region} \
              {{- end }}

              printf "\nSecret {{ .secretname }} has been created\n"
          volumeMounts:
            - name: bucket-secret
              mountPath: "/tmp/bucket-secret"
              readOnly: true
            - name: odf-bucket
              mountPath: /tmp/odf-bucket
      volumes:
        - name: bucket-secret
          secret:
            secretName: {{ .bucket.name }}
        - name: odf-bucket
          configMap:
            name: {{ .bucket.name }}
      restartPolicy: Never
      serviceAccountName: create-odf-secret-sa
{{- end }}
{{- end }}
