{{- with .Values.loggingConfig }}
{{- if and (eq ( .operatorVersion | toString) "6.0") (eq ( .enabled | toString) "true") }}
{{- if .collectorServiceAccount }}
{{- if eq ( .collectorServiceAccount.create | toString) "true" }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .collectorServiceAccount.name | default "cluster-logging-operator" }}
  namespace: openshift-logging
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 4 | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
