{{- with .Values.loggingConfig }}
{{- if and (eq ( .operatorVersion | toString) "6.0") (eq ( .enabled | toString) "true") }}
{{- range .additionalClusterRoles }}

{{- if and (eq ( .type | toString) "application") (eq ( .enabled | toString) "true") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name | default "cluster-logging-write-application-logs" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 4 | quote }}
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - application
    resourceNames:
      - logs
    verbs:
      - create
{{- end }}

{{- if and (eq ( .type | toString) "audit") (eq ( .enabled | toString) "true") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name | default "cluster-logging-write-audit-logs" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 4 | quote }}
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - audit
    resourceNames:
      - logs
    verbs:
      - create
{{- end }}

{{- if and (eq ( .type | toString) "infrastructure") (eq ( .enabled | toString) "true") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name | default "cluster-logging-write-infrastructure-logs" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 4 | quote }}
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - infrastructure
    resourceNames:
      - logs
    verbs:
      - create
{{- end }}

{{- if and (eq ( .type | toString) "editor") (eq ( .enabled | toString) "true") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name | default "clusterlogforwarder-editor-role" }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 4 | quote }}
rules:
  - apiGroups:
      - observability.openshift.io
    resources:
      - clusterlogforwarders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}

{{- end }}
{{- end }}
{{- end }}
