{{- if eq (.Values.tempostack.enabled | toString) "true" }}
{{- if eq (.Values.tempostack.tenants.enabled | toString) "true" }}
{{- with .Values.tempostack }}
{{- $hasReadPermission := false }}
{{- /* Loop through authentication block to find tenants with read permissions */ -}}
{{- range .tenants.authentication }}
  {{- if .permissions }}
    {{- if has "read" .permissions }}
      {{- $hasReadPermission = true }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $hasReadPermission }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-traces-reader
  namespace: {{ .namespace.name }}
  annotations:
    {{- include "tpl.additionalAnnotations" .additionalAnnotations | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" .additionalLabels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .name }}-traces-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
{{- end }}
{{- end }}
{{- end }}
{{- end }}