apiVersion: v2
name: tpl
description: A library that shall collect certain templates to reuse them among different charts.
version: 1.0.15
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/tpl
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/template.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - templates
  - helper
  - subchart
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
    - kind: added
      description: tpl nodeSelector
    - kind: added
      description: tpl for sleeptimer that can be used in jobs
    - kind: added
      description: tpl to set nodeSelector and tolartion annoations for a namespace
    - kind: added
      description: new TPLs to create matchExpressions and matchLabels blocks
