# the name of our job
name: test

# yes, we want to run for all branches and pull requests
on:
  workflow_dispatch:

# we have just our job `test`
jobs:
  test:
    runs-on: ubuntu-latest
    # here is the main section for us, where we spin up the Redpanda instance
    # using the Redpanda GitHub action,pay attention on the `.with.version` key, we are using _latest_ but you can use any Redpanda version
    # tip: version is exactly the same as the Redpanda docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: test 
      run: |
        ls -la 
        rake --version
        rake -v --trace
        ls -la 
